# Generated by Django 2.0 on 2017-12-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
