# Generated by Django 2.0 on 2017-12-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171220_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
